import { UserRole } from "@/types/role";
import React from 'react';
import { BarChart2, Zap, Target, Settings } from 'react-feather';
import Head from 'next/head';

import RolePageLayout from '../components/marketing/RolePageLayout';
import HeroSection from '../components/marketing/HeroSection';
import BenefitsSection from '../components/marketing/BenefitsSection';
import HowItWorksSection from '../components/marketing/HowItWorksSection';
import FAQSection from '../components/marketing/FAQSection';
// import '@/components/ui/Divider';

const PublisherPage: React.FC = () => {
  // Benefits for publishers
  const benefits = [
    {
      title: 'Direct Bitcoin Payments',
      description: 'Receive Bitcoin payments directly to your wallet through the Lightning Network.',
      icon: <Zap className="w-8 h-8" />,
    },
    {
      title: 'Control Your Content',
      description: 'Choose what types of ads appear alongside your content.',
      icon: <Settings className="w-8 h-8" />,
    },
    {
      title: 'Detailed Analytics',
      description: 'Access real-time data on ad performance and audience engagement.',
      icon: <BarChart2 className="w-8 h-8" />,
    },
    {
      title: 'Targeted Reach',
      description: 'Connect with advertisers who want to reach your specific audience.',
      icon: <Target className="w-8 h-8" />,
    },
  ];

  // How it works steps
  const steps = [
    {
      number: 1,
      title: 'Create Your Publisher Account',
      description: 'Sign up with your Nostr key and set up your publisher profile.',
    },
    {
      number: 2,
      title: 'Connect Your Bitcoin Wallet',
      description: 'Link your Lightning wallet to receive payments directly.',
    },
    {
      number: 3,
      title: 'Configure Ad Preferences',
      description: 'Set your ad content preferences and placement options.',
    },
    {
      number: 4,
      title: 'Monetize Your Content',
      description: 'Start earning Bitcoin as ads appear alongside your content.',
    },
  ];

  // FAQ items specific to publishers
  const faqItems = [
    {
      question: 'How much can I earn as a publisher?',
      answer: 'Earnings depend on audience size, engagement rates, and ad types. Publishers typically earn 70-85% of ad revenue generated by their content.',
    },
    {
      question: 'What types of content can I monetize?',
      answer: 'You can monetize blogs, social media posts, videos, podcasts, and any other content that uses the Nostr protocol.',
    },
    {
      question: 'How often will I get paid?',
      answer: 'Payments are processed through the Lightning Network, allowing for frequent micropayments or scheduled larger payments based on your preference.',
    },
    {
      question: 'Can I block certain types of ads?',
      answer: 'Yes, you have full control over the types of ads displayed with your content. You can block specific categories or advertisers.',
    },
    {
      question: 'Do I need technical knowledge to integrate ads?',
      answer: 'No, our platform is designed to be easy to use with simple integration options for all technical skill levels.',
    },
  ];

  return (
    <>
      <Head>
        <title>Publishers - ProofofReach</title>
        <meta name="description" content="Monetize your content with direct Bitcoin payments on the Nostr Ad Marketplace." />
      </Head>

      <RolePageLayout 
        title="Monetize Your Content"
        roleName="Publishers"
        roleColor="bg-green-600"
      >
        {/* Hero Section */}
        <HeroSection
          title="Get Paid For Your Content"
          subtitle="MONETIZE WITH BITCOIN"
          description="Turn your content into income with the Nostr Ad Marketplace. Connect directly with advertisers and receive Bitcoin payments through the Lightning Network."
          ctaText="Start Monetizing"
          ctaLink="/login"
          backgroundColor="bg-gradient-to-r from-green-600 to-green-800"
          imageUrl="/images/publisher-hero.svg"
        />

        <div className="my-16"></div>

        {/* Benefits Section */}
        <BenefitsSection
          title="Benefits for Publishers"
          subtitle="Why monetize with Nostr Ad Marketplace?"
          benefits={benefits}
        />

        <div className="my-16"></div>

        {/* How It Works */}
        <HowItWorksSection
          title="How It Works"
          subtitle="Getting started is simple"
          steps={steps}
        />

        <div className="my-16"></div>

        {/* FAQ Section */}
        <FAQSection
          title="Frequently Asked Questions"
          subtitle="Common questions about being a publisher"
          faqs={faqItems}
        />
      </RolePageLayout>
    </>
  );
};

export default PublisherPage;