import React from 'react';
import { BarChart2, Zap, Target, Settings } from 'react-feather';
import Head from 'next/head';
import Layout from '../components/Layout';
import BenefitsSection from '../components/marketing/BenefitsSection';
import HowItWorksSection from '../components/marketing/HowItWorksSection';
import FAQSection from '../components/marketing/FAQSection';

const PublisherPage: React.FC = () => {
  // Benefits for publishers
  const benefits = [
    {
      title: 'Direct Bitcoin Payments',
      description: 'Receive Bitcoin payments directly to your wallet through the Lightning Network.',
      icon: <Zap className="w-8 h-8" />,
    },
    {
      title: 'Control Your Content',
      description: 'Choose what types of ads appear alongside your content.',
      icon: <Settings className="w-8 h-8" />,
    },
    {
      title: 'Detailed Analytics',
      description: 'Access real-time data on ad performance and audience engagement.',
      icon: <BarChart2 className="w-8 h-8" />,
    },
    {
      title: 'Targeted Reach',
      description: 'Connect with advertisers who want to reach your specific audience.',
      icon: <Target className="w-8 h-8" />,
    },
  ];

  // How it works steps
  const steps = [
    {
      number: 1,
      title: 'Create Your Publisher Account',
      description: 'Sign up with your Nostr key and set up your publisher profile.',
    },
    {
      number: 2,
      title: 'Connect Your Bitcoin Wallet',
      description: 'Link your Lightning wallet to receive payments directly.',
    },
    {
      number: 3,
      title: 'Configure Ad Preferences',
      description: 'Set your ad content preferences and placement options.',
    },
    {
      number: 4,
      title: 'Monetize Your Content',
      description: 'Start earning Bitcoin as ads appear alongside your content.',
    },
  ];

  // FAQ items specific to publishers
  const faqItems = [
    {
      question: 'How much can I earn as a publisher?',
      answer: 'Earnings depend on audience size, engagement rates, and ad types. Publishers typically earn 70-85% of ad revenue generated by their content.',
    },
    {
      question: 'What types of content can I monetize?',
      answer: 'You can monetize blogs, social media posts, videos, podcasts, and any other content that uses the Nostr protocol.',
    },
    {
      question: 'How often will I get paid?',
      answer: 'Payments are processed through the Lightning Network, allowing for frequent micropayments or scheduled larger payments based on your preference.',
    },
    {
      question: 'Can I block certain types of ads?',
      answer: 'Yes, you have full control over the types of ads displayed with your content. You can block specific categories or advertisers.',
    },
    {
      question: 'Do I need technical knowledge to integrate ads?',
      answer: 'No, our platform is designed to be easy to use with simple integration options for all technical skill levels.',
    },
  ];

  return (
    <>
      <Head>
        <title>Publishers - Proof Of Reach</title>
        <meta name="description" content="Monetize your content with direct Bitcoin payments on the Nostr Ad Marketplace." />
      </Head>

      <Layout>
        {/* Hero Section */}
        <div className="bg-gradient-to-br from-gray-900 via-green-900 to-emerald-900 py-20">
          <div className="max-w-7xl mx-auto px-4 text-center">
            <div className="inline-flex items-center bg-green-600/20 text-green-400 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <Zap className="w-4 h-4 mr-2" />
              MONETIZE WITH BITCOIN
            </div>
            <h1 className="text-4xl md:text-6xl font-bold text-white mb-6">
              Get Paid For Your 
              <span className="bg-gradient-to-r from-orange-400 to-orange-600 bg-clip-text text-transparent"> Content</span>
            </h1>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-8 leading-relaxed">
              Turn your content into income with Proof Of Reach. Connect directly with advertisers and receive Bitcoin payments through the Lightning Network.
            </p>
            <a 
              href="/login" 
              className="inline-flex items-center bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700 text-white font-bold py-4 px-8 rounded-lg text-lg transition-all duration-300 transform hover:scale-105 shadow-lg"
            >
              Start Monetizing
            </a>
          </div>
        </div>

        {/* Benefits Section */}
        <div className="py-20 bg-gray-900">
          <div className="max-w-7xl mx-auto px-4">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent mb-4">
                Benefits for Publishers
              </h2>
              <p className="text-xl text-gray-400 max-w-3xl mx-auto">
                Why monetize with Proof Of Reach?
              </p>
            </div>
            <BenefitsSection
              title=""
              subtitle=""
              benefits={benefits}
            />
          </div>
        </div>

        {/* How It Works */}
        <div className="py-20 bg-gray-800">
          <div className="max-w-7xl mx-auto px-4">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-blue-400 to-blue-600 bg-clip-text text-transparent mb-4">
                How It Works
              </h2>
              <p className="text-xl text-gray-400 max-w-3xl mx-auto">
                Getting started is simple
              </p>
            </div>
            <HowItWorksSection
              title=""
              subtitle=""
              steps={steps}
            />
          </div>
        </div>

        {/* FAQ Section */}
        <div className="py-20 bg-gray-900">
          <div className="max-w-7xl mx-auto px-4">
            <FAQSection
              title="Frequently Asked Questions"
              subtitle="Common questions about being a publisher"
              faqs={faqItems}
              maxItems={8}
            />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default PublisherPage;